name = "corporate-hell"
author = "@Ciiina, @wawwior"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5570d1e815c6922cc54e617139feba7876a1a23f70fa4c3a656babfe65c81f21"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
