name = "corporate-hell"
author = "@Ciiina, @wawwior"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e70ac48cf93221973f318dd227378390d29dd82df82c88b78ad5b06643c1c773"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
